// flow-typed signature: d1815973fd49ece8a13f50f0713f2585
// flow-typed version: <<STUB>>/axs-ui_v^1.0.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axs-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'axs-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axs-ui/dist/Button' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/Checkbox' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/Flex' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/Heading' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/index' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/InlineBlock' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/Input' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/Label' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/Progress' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/Radio' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/resets' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/Select' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/Slider' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/Span' {
  declare module.exports: any;
}

declare module 'axs-ui/dist/Textarea' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axs-ui/dist/Button.js' {
  declare module.exports: $Exports<'axs-ui/dist/Button'>;
}
declare module 'axs-ui/dist/Checkbox.js' {
  declare module.exports: $Exports<'axs-ui/dist/Checkbox'>;
}
declare module 'axs-ui/dist/Flex.js' {
  declare module.exports: $Exports<'axs-ui/dist/Flex'>;
}
declare module 'axs-ui/dist/Heading.js' {
  declare module.exports: $Exports<'axs-ui/dist/Heading'>;
}
declare module 'axs-ui/dist/index.js' {
  declare module.exports: $Exports<'axs-ui/dist/index'>;
}
declare module 'axs-ui/dist/InlineBlock.js' {
  declare module.exports: $Exports<'axs-ui/dist/InlineBlock'>;
}
declare module 'axs-ui/dist/Input.js' {
  declare module.exports: $Exports<'axs-ui/dist/Input'>;
}
declare module 'axs-ui/dist/Label.js' {
  declare module.exports: $Exports<'axs-ui/dist/Label'>;
}
declare module 'axs-ui/dist/Progress.js' {
  declare module.exports: $Exports<'axs-ui/dist/Progress'>;
}
declare module 'axs-ui/dist/Radio.js' {
  declare module.exports: $Exports<'axs-ui/dist/Radio'>;
}
declare module 'axs-ui/dist/resets.js' {
  declare module.exports: $Exports<'axs-ui/dist/resets'>;
}
declare module 'axs-ui/dist/Select.js' {
  declare module.exports: $Exports<'axs-ui/dist/Select'>;
}
declare module 'axs-ui/dist/Slider.js' {
  declare module.exports: $Exports<'axs-ui/dist/Slider'>;
}
declare module 'axs-ui/dist/Span.js' {
  declare module.exports: $Exports<'axs-ui/dist/Span'>;
}
declare module 'axs-ui/dist/Textarea.js' {
  declare module.exports: $Exports<'axs-ui/dist/Textarea'>;
}
