// flow-typed signature: 8330e1e82cb04b25b03173d1458d25de
// flow-typed version: <<STUB>>/axs_v^1.0.6/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'axs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axs/dist/Base' {
  declare module.exports: any;
}

declare module 'axs/dist/Block' {
  declare module.exports: any;
}

declare module 'axs/dist/Box' {
  declare module.exports: any;
}

declare module 'axs/dist/config' {
  declare module.exports: any;
}

declare module 'axs/dist/Flex' {
  declare module.exports: any;
}

declare module 'axs/dist/get-border' {
  declare module.exports: any;
}

declare module 'axs/dist/get-color' {
  declare module.exports: any;
}

declare module 'axs/dist/get-display' {
  declare module.exports: any;
}

declare module 'axs/dist/get-radii' {
  declare module.exports: any;
}

declare module 'axs/dist/get-width' {
  declare module.exports: any;
}

declare module 'axs/dist/Heading' {
  declare module.exports: any;
}

declare module 'axs/dist/index' {
  declare module.exports: any;
}

declare module 'axs/dist/Inline' {
  declare module.exports: any;
}

declare module 'axs/dist/InlineBlock' {
  declare module.exports: any;
}

declare module 'axs/dist/parse-props' {
  declare module.exports: any;
}

declare module 'axs/dist/scale-prop' {
  declare module.exports: any;
}

declare module 'axs/dist/Text' {
  declare module.exports: any;
}

declare module 'axs/dist/util/border' {
  declare module.exports: any;
}

declare module 'axs/dist/util/breakpoints' {
  declare module.exports: any;
}

declare module 'axs/dist/util/color' {
  declare module.exports: any;
}

declare module 'axs/dist/util/convert-shorthand-props' {
  declare module.exports: any;
}

declare module 'axs/dist/util/default-config' {
  declare module.exports: any;
}

declare module 'axs/dist/util/display' {
  declare module.exports: any;
}

declare module 'axs/dist/util/font-size' {
  declare module.exports: any;
}

declare module 'axs/dist/util/index' {
  declare module.exports: any;
}

declare module 'axs/dist/util/parse-array-value' {
  declare module.exports: any;
}

declare module 'axs/dist/util/parse-box-props' {
  declare module.exports: any;
}

declare module 'axs/dist/util/parse-props' {
  declare module.exports: any;
}

declare module 'axs/dist/util/parse-text-props' {
  declare module.exports: any;
}

declare module 'axs/dist/util/radii' {
  declare module.exports: any;
}

declare module 'axs/dist/util/scale-prop' {
  declare module.exports: any;
}

declare module 'axs/dist/util/typography' {
  declare module.exports: any;
}

declare module 'axs/dist/util/width' {
  declare module.exports: any;
}

declare module 'axs/dist/withAxs' {
  declare module.exports: any;
}

declare module 'axs/dist/withBox' {
  declare module.exports: any;
}

declare module 'axs/dist/withText' {
  declare module.exports: any;
}

declare module 'axs/test/config' {
  declare module.exports: any;
}

declare module 'axs/test/parse-props' {
  declare module.exports: any;
}

declare module 'axs/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axs/dist/Base.js' {
  declare module.exports: $Exports<'axs/dist/Base'>;
}
declare module 'axs/dist/Block.js' {
  declare module.exports: $Exports<'axs/dist/Block'>;
}
declare module 'axs/dist/Box.js' {
  declare module.exports: $Exports<'axs/dist/Box'>;
}
declare module 'axs/dist/config.js' {
  declare module.exports: $Exports<'axs/dist/config'>;
}
declare module 'axs/dist/Flex.js' {
  declare module.exports: $Exports<'axs/dist/Flex'>;
}
declare module 'axs/dist/get-border.js' {
  declare module.exports: $Exports<'axs/dist/get-border'>;
}
declare module 'axs/dist/get-color.js' {
  declare module.exports: $Exports<'axs/dist/get-color'>;
}
declare module 'axs/dist/get-display.js' {
  declare module.exports: $Exports<'axs/dist/get-display'>;
}
declare module 'axs/dist/get-radii.js' {
  declare module.exports: $Exports<'axs/dist/get-radii'>;
}
declare module 'axs/dist/get-width.js' {
  declare module.exports: $Exports<'axs/dist/get-width'>;
}
declare module 'axs/dist/Heading.js' {
  declare module.exports: $Exports<'axs/dist/Heading'>;
}
declare module 'axs/dist/index.js' {
  declare module.exports: $Exports<'axs/dist/index'>;
}
declare module 'axs/dist/Inline.js' {
  declare module.exports: $Exports<'axs/dist/Inline'>;
}
declare module 'axs/dist/InlineBlock.js' {
  declare module.exports: $Exports<'axs/dist/InlineBlock'>;
}
declare module 'axs/dist/parse-props.js' {
  declare module.exports: $Exports<'axs/dist/parse-props'>;
}
declare module 'axs/dist/scale-prop.js' {
  declare module.exports: $Exports<'axs/dist/scale-prop'>;
}
declare module 'axs/dist/Text.js' {
  declare module.exports: $Exports<'axs/dist/Text'>;
}
declare module 'axs/dist/util/border.js' {
  declare module.exports: $Exports<'axs/dist/util/border'>;
}
declare module 'axs/dist/util/breakpoints.js' {
  declare module.exports: $Exports<'axs/dist/util/breakpoints'>;
}
declare module 'axs/dist/util/color.js' {
  declare module.exports: $Exports<'axs/dist/util/color'>;
}
declare module 'axs/dist/util/convert-shorthand-props.js' {
  declare module.exports: $Exports<'axs/dist/util/convert-shorthand-props'>;
}
declare module 'axs/dist/util/default-config.js' {
  declare module.exports: $Exports<'axs/dist/util/default-config'>;
}
declare module 'axs/dist/util/display.js' {
  declare module.exports: $Exports<'axs/dist/util/display'>;
}
declare module 'axs/dist/util/font-size.js' {
  declare module.exports: $Exports<'axs/dist/util/font-size'>;
}
declare module 'axs/dist/util/index.js' {
  declare module.exports: $Exports<'axs/dist/util/index'>;
}
declare module 'axs/dist/util/parse-array-value.js' {
  declare module.exports: $Exports<'axs/dist/util/parse-array-value'>;
}
declare module 'axs/dist/util/parse-box-props.js' {
  declare module.exports: $Exports<'axs/dist/util/parse-box-props'>;
}
declare module 'axs/dist/util/parse-props.js' {
  declare module.exports: $Exports<'axs/dist/util/parse-props'>;
}
declare module 'axs/dist/util/parse-text-props.js' {
  declare module.exports: $Exports<'axs/dist/util/parse-text-props'>;
}
declare module 'axs/dist/util/radii.js' {
  declare module.exports: $Exports<'axs/dist/util/radii'>;
}
declare module 'axs/dist/util/scale-prop.js' {
  declare module.exports: $Exports<'axs/dist/util/scale-prop'>;
}
declare module 'axs/dist/util/typography.js' {
  declare module.exports: $Exports<'axs/dist/util/typography'>;
}
declare module 'axs/dist/util/width.js' {
  declare module.exports: $Exports<'axs/dist/util/width'>;
}
declare module 'axs/dist/withAxs.js' {
  declare module.exports: $Exports<'axs/dist/withAxs'>;
}
declare module 'axs/dist/withBox.js' {
  declare module.exports: $Exports<'axs/dist/withBox'>;
}
declare module 'axs/dist/withText.js' {
  declare module.exports: $Exports<'axs/dist/withText'>;
}
declare module 'axs/test/config.js' {
  declare module.exports: $Exports<'axs/test/config'>;
}
declare module 'axs/test/parse-props.js' {
  declare module.exports: $Exports<'axs/test/parse-props'>;
}
declare module 'axs/util.js' {
  declare module.exports: $Exports<'axs/util'>;
}
