// flow-typed signature: 3a48de92dfb4a89051ccf1031a4feb40
// flow-typed version: <<STUB>>/cxs_v^3.0.4/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cxs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'cxs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cxs/atomic' {
  declare module.exports: any;
}

declare module 'cxs/dist/atomic/_ref' {
  declare module.exports: any;
}

declare module 'cxs/dist/atomic/index' {
  declare module.exports: any;
}

declare module 'cxs/dist/atomic/shorthands' {
  declare module.exports: any;
}

declare module 'cxs/dist/createCxs' {
  declare module.exports: any;
}

declare module 'cxs/dist/hash' {
  declare module.exports: any;
}

declare module 'cxs/dist/lite/index' {
  declare module.exports: any;
}

declare module 'cxs/dist/lite/rehydrate' {
  declare module.exports: any;
}

declare module 'cxs/dist/monolithic/_mono' {
  declare module.exports: any;
}

declare module 'cxs/dist/monolithic/index' {
  declare module.exports: any;
}

declare module 'cxs/dist/sheet' {
  declare module.exports: any;
}

declare module 'cxs/dist/util' {
  declare module.exports: any;
}

declare module 'cxs/lite' {
  declare module.exports: any;
}

declare module 'cxs/monolithic' {
  declare module.exports: any;
}

declare module 'cxs/packages/cxs-components/dist/index' {
  declare module.exports: any;
}

declare module 'cxs/packages/cxs-components/dist/static' {
  declare module.exports: any;
}

declare module 'cxs/packages/cxs-components/static' {
  declare module.exports: any;
}

declare module 'cxs/packages/react-cxs-hoc/dist/Base' {
  declare module.exports: any;
}

declare module 'cxs/packages/react-cxs-hoc/dist/index' {
  declare module.exports: any;
}

declare module 'cxs/packages/react-cxs-hoc/index' {
  declare module.exports: any;
}

declare module 'cxs/packages/react-cxs/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cxs/atomic.js' {
  declare module.exports: $Exports<'cxs/atomic'>;
}
declare module 'cxs/dist/atomic/_ref.js' {
  declare module.exports: $Exports<'cxs/dist/atomic/_ref'>;
}
declare module 'cxs/dist/atomic/index.js' {
  declare module.exports: $Exports<'cxs/dist/atomic/index'>;
}
declare module 'cxs/dist/atomic/shorthands.js' {
  declare module.exports: $Exports<'cxs/dist/atomic/shorthands'>;
}
declare module 'cxs/dist/createCxs.js' {
  declare module.exports: $Exports<'cxs/dist/createCxs'>;
}
declare module 'cxs/dist/hash.js' {
  declare module.exports: $Exports<'cxs/dist/hash'>;
}
declare module 'cxs/dist/lite/index.js' {
  declare module.exports: $Exports<'cxs/dist/lite/index'>;
}
declare module 'cxs/dist/lite/rehydrate.js' {
  declare module.exports: $Exports<'cxs/dist/lite/rehydrate'>;
}
declare module 'cxs/dist/monolithic/_mono.js' {
  declare module.exports: $Exports<'cxs/dist/monolithic/_mono'>;
}
declare module 'cxs/dist/monolithic/index.js' {
  declare module.exports: $Exports<'cxs/dist/monolithic/index'>;
}
declare module 'cxs/dist/sheet.js' {
  declare module.exports: $Exports<'cxs/dist/sheet'>;
}
declare module 'cxs/dist/util.js' {
  declare module.exports: $Exports<'cxs/dist/util'>;
}
declare module 'cxs/lite.js' {
  declare module.exports: $Exports<'cxs/lite'>;
}
declare module 'cxs/monolithic.js' {
  declare module.exports: $Exports<'cxs/monolithic'>;
}
declare module 'cxs/packages/cxs-components/dist/index.js' {
  declare module.exports: $Exports<'cxs/packages/cxs-components/dist/index'>;
}
declare module 'cxs/packages/cxs-components/dist/static.js' {
  declare module.exports: $Exports<'cxs/packages/cxs-components/dist/static'>;
}
declare module 'cxs/packages/cxs-components/static.js' {
  declare module.exports: $Exports<'cxs/packages/cxs-components/static'>;
}
declare module 'cxs/packages/react-cxs-hoc/dist/Base.js' {
  declare module.exports: $Exports<'cxs/packages/react-cxs-hoc/dist/Base'>;
}
declare module 'cxs/packages/react-cxs-hoc/dist/index.js' {
  declare module.exports: $Exports<'cxs/packages/react-cxs-hoc/dist/index'>;
}
declare module 'cxs/packages/react-cxs-hoc/index.js' {
  declare module.exports: $Exports<'cxs/packages/react-cxs-hoc/index'>;
}
declare module 'cxs/packages/react-cxs/dist/index.js' {
  declare module.exports: $Exports<'cxs/packages/react-cxs/dist/index'>;
}
